In [1]:
import numpy as np
# Вхідна матриця
matrix = np.array([[2, 5, 7],
                   [6, 3, 4],
                   [5, -2, -3]])
# Знаходження оберненої матриці
inverse_matrix = np.linalg.inv(matrix)
print("Матриця:")
print(matrix)
print("\nОбернена матриця:")
print(inverse_matrix)


Матриця:
[[ 2  5  7]
 [ 6  3  4]
 [ 5 -2 -3]]

Обернена матриця:
[[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]
