In [1]:
import numpy as np
# Вхідна матриця
matrix = np.array([[1, 2, 3, 4],
                   [3, -1, 2, 5],
                   [1, 2, 3, 4],
                   [1, 3, 4, 5]])
# Знаходження рангу матриці
matrix_rank = np.linalg.matrix_rank(matrix)
print("Матриця:")
print(matrix)
print("\nРанг матриці:", matrix_rank)


Матриця:
[[ 1  2  3  4]
 [ 3 -1  2  5]
 [ 1  2  3  4]
 [ 1  3  4  5]]

Ранг матриці: 2
