In [1]:
import numpy as np

def count_negatives(matrix):
    # Визначення кількості негативних елементів у кожному стовпці та рядку
    row_negatives = np.sum(matrix < 0, axis=1)
    col_negatives = np.sum(matrix < 0, axis=0)
    return row_negatives, col_negatives

# Розмір матриці (N рядків і M стовпців)
N = 4
M = 5

# Створення матриці з випадковими елементами
matrix_A = np.random.randint(-10, 10, size=(N, M))

# Виведення початкової матриці
print("Початкова матриця:")
print(matrix_A)

# Визначення кількості негативних елементів
row_negatives, col_negatives = count_negatives(matrix_A)

# Виведення результатів
print("\nКількість негативних елементів в кожному рядку:")
print(row_negatives)
print("\nКількість негативних елементів в кожному стовпці:")
print(col_negatives)


Початкова матриця:
[[ -3  -1  -5   3 -10]
 [ -6   7  -8   7   6]
 [-10   1  -2   7  -5]
 [  9  -2   6   4  -2]]

Кількість негативних елементів в кожному рядку:
[4 2 3 2]

Кількість негативних елементів в кожному стовпці:
[3 2 3 0 3]
