In [1]:
import numpy as np
# Вхідні матриці
matrix1 = np.array([[3, 5],
                    [6, -1]])
matrix2 = np.array([[2, 1],
                    [-3, 2]])
# Знаходження добутку матриць
result = np.matmul(matrix1, matrix2)
print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)
print("\nДобуток матриць:")
print(result)


Перша матриця:
[[ 3  5]
 [ 6 -1]]

Друга матриця:
[[ 2  1]
 [-3  2]]

Добуток матриць:
[[-9 13]
 [15  4]]
