In [1]:
import numpy as np

A = np.matrix([[1,1,1], [0,1,1], [0,0,1]])
B = np.matrix([[7,5,3],[0,7,5],[0,0,7]])
print("Матриця A:\n",A)
print("Матриця B:\n",B)

AB_matrix = A.dot(B)
BA_matrix = B.dot(A)
C = AB_matrix - BA_matrix
print("Матриця C:\n",C)


Матриця A:
 [[1 1 1]
 [0 1 1]
 [0 0 1]]
Матриця B:
 [[7 5 3]
 [0 7 5]
 [0 0 7]]
Матриця C:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
