In [7]:
import numpy as np
# Вхідна матриця
matrix = np.array([[2, 4, 5],
                   [1, 1, 2],
                   [2, 4, 3]])
# Знаходження визначника матриці
determinant = np.linalg.det(matrix)
print("Матриця:")
print(matrix)
print("\nВизначник матриці:", determinant)


Матриця:
[[2 4 5]
 [1 1 2]
 [2 4 3]]

Визначник матриці: 4.0
