In [1]:
import numpy as np
# Вхідна матриця
matrix = np.array([[2, 3, 4, 1],
                   [1, 2, 3, 4],
                   [3, 4, 1, 2],
                   [4, 1, 2, 3]])
# Знаходження визначника матриці
determinant = np.linalg.det(matrix)
print("Матриця:")
print(matrix)
print("\nВизначник матриці:", determinant)


Матриця:
[[2 3 4 1]
 [1 2 3 4]
 [3 4 1 2]
 [4 1 2 3]]

Визначник матриці: -160.00000000000009
